### ISSUE TITLE
Fast boot?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [albedozero/squishbox#2]
This project looks cool, does the box boot quickly? I'm used to Rpi taking 60s to boot

**Comment by albedozero** [comment]
I'm using pretty much a vanilla [Raspbian Buster Lite](https://www.raspberrypi.org/downloads/raspbian/) on my latest build and by creating a service to run the squishbox.py script early during startup it [starts in ~7 seconds](http://geekfunklabs.com/2020/04/14/faster-startup/). If you have other software running on your Pi this can affect things.
